# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['do_before']},
        ),
    ]
