# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170822_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
