# Generated by Django 2.1.4 on 2019-04-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170822_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='finished_date',
            new_name='finished_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_date',
            new_name='updated_on',
        ),
    ]
